/*

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

 */

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
	var letters = "abcdefghijklmnopqrstuvwxyz".split("");
	sConcatT = s.concat(t);
	extraLetter = 0;
	
	for (var i = 0; i < sConcatT.length; i++) {
		extraLetter ^= letters.indexOf(sConcatT.charAt(i));
	}
	
	return letters[extraLetter];
};